feat: cd app store

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -25,6 +25,32 @@ definitions:
       - secrets
       - emails
   scripts:
+    - &change_build_number_pubspec_ios
+      name: Change the build number in pubspec.yaml for iOS
+      script: | 
+        LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number $APP_APPLE_ID)
+        UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
+        cd ./ios # avgtool must run in the folder where xcodeproj file is located
+        agvtool new-version -all $UPDATED_BUILD_NUMBER
+        echo "🔢 Using build number: $UPDATED_BUILD_NUMBER"
+        dart run tools/dart_tools/lib/set_build_number_pubspec.dart $UPDATED_BUILD_NUMBER
+
+    - &change_build_number_pubspec_android
+      name: Change the build number in pubspec.yaml for Android
+      script: | 
+        LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+        if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]
+          then
+            # fallback in case no build number was found from Google Play.
+            # Alternatively, you can `exit 1` to fail the build
+            # BUILD_NUMBER is a Codemagic built-in variable tracking the number of
+            # times this workflow has been built
+            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+        fi
+        echo "🔢 Using build number: $UPDATED_BUILD_NUMBER"
+        dart run tools/dart_tools/lib/set_build_number_pubspec.dart $UPDATED_BUILD_NUMBER 
     - &sync
       name: Run pub get and gen files
       script: make sync
@@ -118,76 +144,80 @@ definitions:
         failure: true
 
 workflows:
-  distribution_staging_ios:
-    name: Distribution Staging (iOS)
-    <<: *instance_mac_os
-    environment:
-      <<: *env_config
-      ios_signing:
-        provisioning_profiles:
-          - ios_staging_adhoc_profile
-        certificates:
-          - ios_production_p12
-    scripts:
-      - *sync
-      - *install_pods
-      - *set_up_code_signing_settings_on_xcode_project
-      - *decode_dart_defines
-      - *build_stg_ipa
-    artifacts:
-      - build/ios/ipa/*.ipa
-      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
-    publishing:
-      <<: *email_release
-
-  distribution_staging_android:
-    name: Distribution Staging (Android)
-    environment:
-      <<: *env_config
-      android_signing:
-        - mykey
-    scripts:
-      - *setup_local_properties
-      - *decode_dart_defines
-      - *sync
-      - *build_stg_apk
-    artifacts:
-      - build/app/outputs/flutter-apk/*.apk
-    publishing:
-      <<: *email_release
-
-  distribution_staging:
-    name: Distribution Staging
+  distribution_qa:
+    name: Distribution Qa
     triggering:
       events:
         - pull_request
       branch_patterns:
-        - pattern: 'build/stg/*'
+        - pattern: 'build/qa/*'
           include: true
           source: true 
     <<: *instance_mac_os
     environment:
       <<: *env_config
       android_signing:
-        - mykey
+        - android_keystore
       ios_signing:
         provisioning_profiles:
-          - ios_staging_adhoc_profile
+          - ios_production_distribution_profile
         certificates:
-          - ios_production_p12
+          - ios_p12
     scripts:
+      - *set_up_code_signing_settings_on_xcode_project
       - *setup_local_properties
       - *sync
       - *install_pods
-      - *set_up_code_signing_settings_on_xcode_project
       - *decode_dart_defines
-      - *build_stg_ipa
-      - *build_stg_apk 
+      - *build_qa_ipa
+      - *build_qa_apk
     artifacts:
       - build/ios/ipa/*.ipa
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
       - build/app/outputs/flutter-apk/*.apk
     publishing:
+      <<: *email_release
+
+  distribution_store_staging:
+    name: Distribution Store Staging
+    <<: *instance_mac_os
+    integrations:
+      app_store_connect: app-store-connect
+    environment:
+      <<: *env_config
+      android_signing:
+        - android_keystore
+      ios_signing:
+        provisioning_profiles:
+          - ios_production_distribution_profile
+        certificates:
+          - ios_p12
+    scripts:
+      - *set_up_code_signing_settings_on_xcode_project
+      - *setup_local_properties
+      - *sync
+      - *install_pods
+      - *decode_dart_defines
+      - *change_build_number_pubspec_ios
+      - *build_stg_ipa
+      - *change_build_number_pubspec_android
+      - *build_stg_aab
+    artifacts:
+      - build/ios/ipa/*.ipa
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
+      - build/app/outputs/bundle/stagingRelease/*.aab
+    publishing:
+      google_play:
+        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+        track: internal
+        submit_as_draft: true
+      app_store_connect:
+        auth: integration
+        submit_to_testflight: true
+        beta_groups:
+          - "testers"
+        expire_build_submitted_for_review: false
+        submit_to_app_store: false
       <<: *email_release
 
   distribution_store_production:
@@ -205,12 +235,12 @@ workflows:
     environment:
       <<: *env_config
       android_signing:
-        - mykey
+        - android_keystore
       ios_signing:
         provisioning_profiles:
-          - ios_distribution_profile
+          - ios_production_distribution_profile
         certificates:
-          - ios_production_p12
+          - ios_p12
     scripts:
       - *setup_local_properties
       - *sync
@@ -232,8 +262,8 @@ workflows:
       app_store_connect:
         auth: integration
         submit_to_testflight: true
-        # beta_groups:
-        #   - "testers"
+        beta_groups:
+          - "testers"
         expire_build_submitted_for_review: false
         submit_to_app_store: false
       <<: *email_release
